language: python

os:
  - linux

env:
  global:
    - HELM_VERSION=2.13.0
    - APPR_VERSION=0.7.4
    - APPR_URL=https://github.com/app-registry/appr/releases/download/v$APPR_VERSION/appr-linux-x64
    - CHART_VERSION=0.0.1
    - secure: "rSnvhEdRjgC1z/krmmgM9ilsQmbxAb/gANk6e+Uow2y/hMHl3WwgG/plHrfpdiawri7ZGe8Bm1O0Y3w343pV8UCHa4Ezrz0Ceifcs8wLC11ZNDiZk+svLQ/R8HyQu73tpilPrkaqLsQ7rddieGOBKgFTTvvtQN4HqC3POkLOjKcrGkYhWDciOemgmyYQjqVMBJiTTTZ5S2o9PFPN3hTqYGbWGRWoXPLz0PKgq0U1CEa2PLMBUo6fiXuVSdwN7j3JsNoJH03S6How0vabgU/xOqHwjyDrMsJm4MjKxkEvmZa5OudYAx352f2bMWmmhM3mpCYbfbzaLKB6X5lGPiWfYAuPZduhsr51tRTSCXroxv+mwtGViufLnj8UVnXerSKMqTaPx0jYPE1QZFSj+2JWnQIoqT+5S05SAxMnVwEKq8Usi2u4f/Xw5RNHKIGlBx+LgDan+V0KQ/9lYEREHgup9oROxoA6lpyovHJ6zNwDOJbEUA8DRBSlw9Tjd7PjcYdSmLT0dO1zIKncT7RvhWHW7F6B4uPBMV12VVhSgEiqxBmDiwQmIcbD09t5WP2L2fyTJt5wnpRkIBy76nMoRVwIpXme6JHVGru/Tjj10wq7UthzuVcP84hk4ggeoDK5iH2dJR8USwZYMnCx+XSB+vqU9G4Uc/yE18359wUtSuL0dMs="

install:
  - curl "https://kubernetes-helm.storage.googleapis.com/helm-v${HELM_VERSION}-linux-amd64.tar.gz" | tar zx
  - PATH=`pwd`/linux-amd64/:$PATH
  - mkdir -p ~/.helm/plugins
  - git clone https://github.com/app-registry/appr-helm-plugin.git ~/.helm/plugins/registry
  - curl -L "$APPR_URL" -o ~/.helm/plugins/registry/appr
  - chmod +x ~/.helm/plugins/registry/appr
  - helm version --client
  - helm init --client-only
  - helm registry version quay.io

script:
  - helm lint --set prometheusOperator.create=true,skipper.ingressClass=skipper,skipper.logLevel=INFO,rbac.create=true skipper/
  - helm registry login -u baez -p "$QUAY_IO_TOKEN" quay.io
  - cd skipper/
  - helm registry delete-package quay.io/baez/skipper@${CHART_VERSION} || true
  - helm registry push -v ${CHART_VERSION} --namespace baez --channel alpha quay.io

deploy:
  provider: script
  script:
    - helm registry login -u baez+travis -p "$QUAY_IO_TOKEN" quay.io
    - cd skipper/
    - helm registry push -v ${TRAVIS_TAG} --namespace baez --channel stable quay.io
  on:
    tags: true
    all_branches: false
